# 使用yaml做配置项
server:
  bind: "127.0.0.1"
  port: 9000
  mode: release
  cors:
    origins: ["*"]
    methods: ["PUT", "PATCH"]
# 数据库配置项
db:
  type: mysql
  mysql:
    dbname: "example"
    password: "root1234"
    username: "root"
    port: 3306
    host: "127.0.0.1"
log:
  # 默认路径是运行程序的目录
  #  path: ./logging
  infoFilename: info.log
  errorFilename: error.log
  maxSize: 10
  maxBackups: 5
  maxAge: 10
  level: info